server:
  port: 8080

spring:
  application:
    name: mywebsite
  # 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/my_test_database?useSSL=false&serverTimezone=UTC
    username: root
    password: s1050218
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000
      password:
  mail:
    host: smtp.office365.com
    port: 587
    username: zyhhenry42@hotmail.com
    password: s1050218
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.office365.com
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trusted: # 设置信任的包列表
        - com.zyh.mywebsite.entity

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.zyh.mywebsite.mapper
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  extension:
    enabled: true
    mapper-package: com.zyh.mywebsite.mapper
    data-permission:
      enabled: true

